# Generated by Django 4.2.2 on 2023-06-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indica',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
