# Generated by Django 4.2.2 on 2023-06-15 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_amount_country_delete_countryrank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
    ]
