# Generated by Django 4.2.2 on 2023-06-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_year_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='country',
        ),
        migrations.AddField(
            model_name='year',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.indica'),
        ),
    ]
