# Generated by Django 4.2.2 on 2023-06-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_year_country_year_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
